name: Auto Merge and Test

on: 
    pull_request:
        branches:
            - development
        types:
            - opened
            - synchronize
            - reopened
jobs:
    test-and-merge:
        runs-on: ubuntu-latest
        
        steps:
            # Step 1: Checkout code
            - name: Checkout code
              uses: actions/checkout@v3
            
            # Step 2: Setup up the required environment 
            - name: Setup up python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            # Step 3: Install dependencies 
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            # Step 4: Run Test
            - name: Run tests
              run : pytest

            # Step 5: Automatically merge if test pass
            - name: Merge branch if tests pass
              if: success()
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git checkout development
                git merge ${{ github.head_ref }}
                git push origin development
            
            # Step 6 Delete the feature branch after merging
            - name: Delete the feature branch
              if: success()
              run: |
                git push origin --delete ${{ github.head_ref }}